### ISSUE TITLE
'Round a number to 2 decimal places' Challenge

### ISSUE THREAD

**Issue by susansiow** [kvdos/JSchallenger#1]
Hi @kvdos 

First of all, thanks for the wonderful JS challenge website - https://www.jschallenger.com/ ! :)

When you are free, please have a look of the following issues:

1. The toFixed() method should solve the challenge, however it doesn't.

<img width="582" alt="2" src="https://user-images.githubusercontent.com/53169547/160324823-8e9a981f-21ae-4dc2-91a2-21030a513947.png">

2. Looks like the link of 'Round a number to 2 decimal places' has an error too.

<img width="376" alt="1" src="https://user-images.githubusercontent.com/53169547/160324884-244ba422-f09b-4614-b976-4289fb5b9aef.png">

Many thanks!

**Comment by kvdos** [comment]
Hi @susansiow 
No need to thank me anything as this website is not mine. I just provide people with the solutions to avoid the pain of not finding the right solution after trying. The author is Erik Kückelheim.

I think you are correct, though you might be forgetting to convert the String that you get to a Number. toFixed() returns a String. So try Number(a.toFixed(2)) or +a.toFixed(2);

Good luck with the challenges.

**Comment by susansiow** [comment]
Thanks for the kind clarification!
