### ISSUE TITLE
Site error

### ISSUE THREAD

**Issue by derynL** [kvdos/JSchallenger#5]
I've just paid for your 'preium' service and now find that I can't attempt any of the challenges, because a popup error keeps triggering and can't be removed - [follow link](https://www.dropbox.com/s/mkrgfteep851pkh/jschallenger.png?dl=0) for screenshot. Hope it gets fixed soon!

**Comment by kvdos** [comment]
Hi,
I don't own JSChalleger and am not responsible of it in any way, I'm just someone who did the challenges a while ago and posted the solutions back then.
